name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'examples*/**'
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'

env:
  basepython: 3.9

jobs:
  lint:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: Code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install base python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.basepython}}

      - name: prepare the environment
        run: |
          pip install -U setuptools pip poetry tox-docker tox-poetry
          poetry config virtualenvs.create false
          poetry install
      - name: lint
        run: tox -e linters

  tests:
    name: Test on ${{ matrix.platform }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.platform }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    strategy:
      matrix:
        platform: ['ubuntu-20.04']
        python: ['3.7', '3.8', '3.9', '3.10', '3.11']
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python}}
          architecture: x64

      - name: Prepare environment
        run: |
          pip install -U setuptools pip poetry tox-docker tox-poetry
          poetry config virtualenvs.create false
          poetry install
      - name: Run tests
        run: tox -e cover
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: matrix.python == '3.9' && matrix.platform != 'macos-11'
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOVTOKEN }}
